style_edition = "2024"
use_small_heuristics = "Max"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
unstable_features = true
