[build-system]
requires = ["maturin>=1.3,<2.0"]
build-backend = "maturin"

[project]
name = "windows-capture"
version = "1.3.6"
description = "Fastest Windows Screen Capture Library For Python ðŸ”¥"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [{ name = "NiiightmareXD" }]
keywords = ["screen", "capture", "screenshot", "graphics", "windows"]
dependencies = ["numpy", "opencv-python"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: GPU",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Graphics :: Capture",
    "Topic :: Multimedia :: Graphics :: Capture :: Screen Capture",
    "Topic :: Multimedia :: Video :: Capture",
]

[tool.maturin]
features = ["pyo3/extension-module"]
